GET http://localhost:8080/contacts

###

GET http://localhost:8080/contacts/678bf5d3c61a7c166448180b

###

POST http://localhost:8080/contacts HTTP/1.1
content-type: application/json

{
    "firstName":"Vash", "lastName":"Stampede", "email":"humanoid@typhoon.com", "favoriteColor":"Red", "birthday":"07/21/2455"
}

###

PUT http://localhost:8080/contacts/679058f33a16bda5640e554c HTTP/1.1
content-type: application/json

{
    "firstName":"Shirou", "lastName":"Emiya", "email":"hero@justice.com", "favoriteColor":"Black", "birthday":"01/30/2004"
}

### 

DELETE http://localhost:8080/contacts/679ee2a0565d44741bd6d980 HTTP/1.1


###

GET https://cse341-1ptd.onrender.com/contacts

###

GET http://cse341-1ptd.onrender.com/contacts/678bf5d3c61a7c166448180b

### //Render

POST http://cse341-1ptd.onrender.com/contacts HTTP/1.1
content-type: application/json

{
    "firstName":"Vash", "lastName":"Stampede", "email":"humanoid@typhoon.com", "favoriteColor":"Red", "birthday":"07/21/2455"
}

###

PUT http://cse341-1ptd.onrender.com/contacts/6793f775ccdf5e4915c44146 HTTP/1.1
content-type: application/json

{
    "firstName":"Spike",
     "lastName":"Spiegel",
      "email":"cowboy@bebop.biz",
       "favoriteColor":"Yellow",
        "birthday":"09/26/2044"
}

### 

DELETE http://cse341-1ptd.onrender.com/contacts/6793f775ccdf5e4915c44146 HTTP/1.1